# Generated by Django 5.2 on 2026-03-22 07:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iga", "0001_initial"),
        ("schools", "0004_phase4_communications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="activitybudget",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="activityexpense",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="inventorystock",
            name="quantity_available",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="inventorystock",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="producesale",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecord",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="schools.school",
            ),
        ),
    ]
