# Generated by Django 5.2 on 2025-09-09 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('academic_year', models.IntegerField(default=2025)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=2)),
                ('class_position', models.IntegerField(blank=True, null=True)),
                ('stream_position', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('head_teacher_comment', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Report',
                'verbose_name_plural': 'Student Reports',
                'db_table': 'student_reports',
                'ordering': ['-academic_year', '-term', 'student'],
            },
        ),
    ]
