<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-09 14:19

import django.core.validators
=======
# Generated by Django 5.2 on 2025-07-18 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
=======
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scores', to='students.student')),
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'scores',
                'ordering': ['-created_at'],
<<<<<<< HEAD
=======
                'unique_together': {('student', 'exam')},
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('academic_year', models.IntegerField(default=2025)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=2)),
                ('class_position', models.IntegerField(blank=True, null=True)),
                ('stream_position', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('head_teacher_comment', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
=======
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student')),
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1
            ],
            options={
                'verbose_name': 'Student Report',
                'verbose_name_plural': 'Student Reports',
                'db_table': 'student_reports',
                'ordering': ['-academic_year', '-term', 'student'],
<<<<<<< HEAD
=======
                'unique_together': {('student', 'term', 'academic_year')},
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1
            },
        ),
    ]
