# Generated by Django 5.2 on 2026-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentreport",
            name="academic_year",
            field=models.IntegerField(default=2026),
        ),
    ]
