from django.urls import path
from .views import (
    ActivityLogListView,
    AtRiskSchoolsView,
    AvailableStaffView,
    LeadConvertView,
    LeadListCreateView,
    LeadStageTransitionView,
    OnboardingProgressDetailView,
    OnboardingStepProcessView,
    SchoolCreateView,
    SchoolDetailView,
    SchoolHealthCalculateView,
    SchoolHealthOverviewView,
    SchoolTaskListCreateView,
    SchoolTaskStatusView,
    SchoolTransferView,
    SchoolUpsellOpportunityDetectView,
    SchoolUpsellOpportunityListView,
    StaffCapacityAlertsView,
    StaffWorkloadDetailView,
)

urlpatterns = [
    path('', SchoolDetailView.as_view(), name='school-detail'),
    path('create/', SchoolCreateView.as_view(), name='school-create'),
    path('leads/', LeadListCreateView.as_view(), name='lead-list-create'),
    path('leads/<int:lead_id>/convert/', LeadConvertView.as_view(), name='lead-convert'),
    path('leads/<int:lead_id>/stage/', LeadStageTransitionView.as_view(), name='lead-stage-transition'),
    path('onboarding/<int:school_id>/', OnboardingProgressDetailView.as_view(), name='onboarding-progress-detail'),
    path('onboarding/<int:school_id>/steps/', OnboardingStepProcessView.as_view(), name='onboarding-step-process'),
    path('tasks/', SchoolTaskListCreateView.as_view(), name='school-task-list-create'),
    path('tasks/<int:task_id>/status/', SchoolTaskStatusView.as_view(), name='school-task-status'),
    path('activity-logs/', ActivityLogListView.as_view(), name='activity-log-list'),
    path('staff/<int:staff_id>/workload/', StaffWorkloadDetailView.as_view(), name='staff-workload-detail'),
    path('staff/available/', AvailableStaffView.as_view(), name='available-staff'),
    path('staff/capacity-alerts/', StaffCapacityAlertsView.as_view(), name='staff-capacity-alerts'),
    path('health/at-risk/', AtRiskSchoolsView.as_view(), name='school-health-at-risk'),
    path('<int:school_id>/health/', SchoolHealthOverviewView.as_view(), name='school-health-overview'),
    path('<int:school_id>/health/calculate/', SchoolHealthCalculateView.as_view(), name='school-health-calculate'),
    path('<int:school_id>/upsell/', SchoolUpsellOpportunityListView.as_view(), name='school-upsell-list'),
    path('<int:school_id>/upsell/detect/', SchoolUpsellOpportunityDetectView.as_view(), name='school-upsell-detect'),
    path('<int:school_id>/transfer/', SchoolTransferView.as_view(), name='school-transfer'),
]