# Generated by Django 5.2 on 2025-07-13 09:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('grade_level', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=2025)),
                ('capacity', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='students.class')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'db_table': 'streams',
                'ordering': ['class_assigned', 'name'],
                'unique_together': {('name', 'class_assigned', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path)),
                ('kcpe_index', models.CharField(blank=True, help_text='KCPE Index Number', max_length=20)),
                ('admission_year', models.IntegerField(default=2025)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number', regex='^\\+?254[0-9]{9}$|^0[0-9]{9}$')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(default='Parent', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class')),
                ('current_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.stream')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('promotion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='students.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='students.class')),
            ],
            options={
                'verbose_name': 'Student Promotion',
                'verbose_name_plural': 'Student Promotions',
                'db_table': 'student_promotions',
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='students.class')),
                ('from_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='students.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='students.class')),
                ('to_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='students.stream')),
            ],
            options={
                'verbose_name': 'Student Transfer',
                'verbose_name_plural': 'Student Transfers',
                'db_table': 'student_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
