# Generated by Django 5.2 on 2025-07-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(default='current', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
            preserve_default=False,
        ),
    ]
