# Generated by Django 5.2 on 2025-09-09 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjectallocation',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsubjectallocation',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class'),
        ),
        migrations.AddField(
            model_name='classsubjectallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='classsubjectallocation',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='students.class'),
        ),
        migrations.AddField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classsubjectallocation',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.stream'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.stream'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportroute'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='from_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='students.class'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='to_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='students.class'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='from_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='students.class'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='from_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='students.stream'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='to_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='students.class'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='to_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='students.stream'),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('name', 'class_assigned', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectallocation',
            unique_together={('academic_year', 'term', 'school_class', 'stream', 'subject')},
        ),
    ]
