# Generated by Django 5.2 on 2025-07-13 11:15

from django.db import migrations,models

def set_default_school(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    Stream = apps.get_model('students', 'Stream')
    
    # Get or create a default school
    default_school, _ = School.objects.get_or_create(
        name='Default School',
        defaults={'code': 'DEF'}
    )
    
    # Update all existing streams
    Stream.objects.update(school=default_school)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_stream_school'),
    ]

    operations = [
         migrations.AddField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(
                to='schools.School',
                on_delete=models.CASCADE,
                null=True  # Allow null temporarily
            ),
        ),
        migrations.RunPython(set_default_school),
        migrations.AlterField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(
                to='schools.School',
                on_delete=models.CASCADE,
                null=False  # Make non-nullable after data migration
            ),
        ),
    ]
