# Generated by Django 5.2 on 2026-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_class_name_unique_per_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_year",
            field=models.IntegerField(default=2026),
        ),
    ]
