# Generated by Django 5.2 on 2025-07-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_stream_school'),
    ]

    operations = [
    ]
