# Generated by Django 5.2 on 2026-05-14

from django.db import migrations, models
from django.db.models.expressions import RawSQL


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_stream_year_alter_student_admission_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                db_default=RawSQL("public.generate_admission_number()", []),
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
