# Generated by Django 5.2 on 2026-05-14

from django.db import migrations, models
from django.db.models.expressions import RawSQL

class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_alter_stream_year_alter_student_admission_year"),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                schema_editor.execute(
                    "CREATE SEQUENCE IF NOT EXISTS admission_number_seq START 1;"
                    "CREATE OR REPLACE FUNCTION public.generate_admission_number() "
                    "RETURNS text "
                    "LANGUAGE plpgsql "
                    "AS $$ "
                    "BEGIN "
                    "    RETURN to_char(CURRENT_DATE, 'YYYY') || LPAD(nextval('admission_number_seq')::text, 6, '0'); "
                    "END; "
                    "$$;"
                ) if schema_editor.connection.vendor == 'postgresql' else None
            ),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
