# Generated by Django 5.2 on 2026-05-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_stream_year_alter_student_admission_year'),
        ('students', '0006_alter_student_admission_number_db_default'),
    ]

    operations = [
    ]
