# Generated by Django 6.0.5 on 2026-06-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_merge_20260529_1445'),
        ('students', '0008_setup_adm_format'),
    ]

    operations = [
    ]
