# Generated by Django 5.2 on 2026-07-09 14:48

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_merge_0007_merge_20260529_1445_0008_setup_adm_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                db_default=django.db.models.expressions.RawSQL(
                    "public.generate_admission_number()", []
                ),
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
