# Generated by Django 5.2 on 2026-05-25 21:31

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_initial'),
        ('schools', '0004_phase4_communications'),
        ('students', '0005_alter_student_admission_number_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIngressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mpesa', 'M-PESA Paybill'), ('kcb_buni', 'KCB Buni')], db_index=True, max_length=20)),
                ('short_code', models.CharField(help_text='Paybill or merchant code extracted from the raw payload.', max_length=50)),
                ('raw_payload', models.JSONField(help_text='Full original webhook body.')),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the inbound request.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_school', models.ForeignKey(blank=True, help_text='Set by PaymentProcessor after routing to the correct school. NULL = routing failed or not yet resolved. Filter resolved_school__isnull=True to find unresolved ingestions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingress_logs', to='schools.school')),
            ],
            options={
                'verbose_name': 'Payment Ingress Log',
                'verbose_name_plural': 'Payment Ingress Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'M-PESA Paybill'), ('kcb_buni', 'KCB Buni')], db_index=True, max_length=20)),
                ('short_code', models.CharField(help_text='Paybill number (MPESA) or merchant code (KCB Buni).', max_length=50)),
                ('account_name', models.CharField(help_text='Display name, e.g. "ABC Academy Fees".', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('sms_api_url', models.CharField(blank=True, help_text='School-specific SMS provider HTTP endpoint. Leave blank to use system Twilio.', max_length=500)),
                ('sms_api_key', models.CharField(blank=True, max_length=500)),
                ('sms_sender_id', models.CharField(blank=True, max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Payment Config',
                'verbose_name_plural': 'School Payment Configs',
                'unique_together': {('provider', 'short_code')},
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Format: "{provider}:{transaction_code}". Global dedup key.', max_length=200, unique=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-PESA Paybill'), ('kcb_buni', 'KCB Buni')], db_index=True, max_length=20)),
                ('transaction_code', models.CharField(help_text='Transaction reference from the payment provider.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(blank=True, help_text='Sender phone number (may be masked by provider).', max_length=20)),
                ('reference', models.CharField(help_text='Account reference entered by payer, normalised to UPPER. Should equal admission_number.', max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('DUPLICATE', 'Duplicate'), ('INVALID_REFERENCE', 'Invalid Reference'), ('UNRESOLVED_STUDENT', 'Unresolved Student'), ('RECONCILED', 'Reconciled')], db_index=True, default='RECEIVED', max_length=30)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable error detail for non-RECONCILED statuses.')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('system_version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.OneToOneField(blank=True, help_text='Linked fees ledger entry after successful reconciliation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_event', to='fees.paymenttransaction')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(blank=True, help_text='Resolved by reconciliation. NULL if UNRESOLVED_STUDENT or INVALID_REFERENCE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='students.student')),
                ('ingress_log', models.OneToOneField(help_text='Link back to the raw webhook log.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_event', to='payments.paymentingresslog')),
                ('payment_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='payments.schoolpaymentconfig')),
            ],
            options={
                'verbose_name': 'Payment Event',
                'verbose_name_plural': 'Payment Events',
                'ordering': ['-created_at'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
