# Generated by Django 6.0.5 on 2026-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentevent_sms_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-PESA Paybill'), ('kcb_buni', 'KCB Buni'), ('manual', 'Manual Entry')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentingresslog',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-PESA Paybill'), ('kcb_buni', 'KCB Buni'), ('manual', 'Manual Entry')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolpaymentconfig',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-PESA Paybill'), ('kcb_buni', 'KCB Buni'), ('manual', 'Manual Entry')], db_index=True, max_length=20),
        ),
    ]
