# Generated by Django 6.0.5 on 2026-07-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_auth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entity_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('PENDING_EMAIL_VERIFICATION', 'Pending Email Verification'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('LOCKED', 'Locked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=30),
        ),
    ]
