# Generated by Django 6.0.5 on 2026-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0005_activitylog_ip_address_activitylog_user_agent'),
        ('users', '0007_user_force_password_change_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent'), ('external_contact', 'External Contact')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NOT_ENABLED', 'Not Enabled'), ('INVITED', 'Invited'), ('PENDING_EMAIL_VERIFICATION', 'Pending Email Verification'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('LOCKED', 'Locked'), ('EXPIRED', 'Expired')], db_index=True, default='NOT_ENABLED', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_type__gt', ''), ('entity_id__isnull', False)), fields=('entity_type', 'entity_id'), name='users_unique_entity_link'),
        ),
    ]
