# Generated by Django 5.2 on 2025-07-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower number = higher payment priority')),
                ('fee_applicable', models.BooleanField(default=True, help_text='If ticked, this votehead appears on fees structures and receipts')),
                ('student_group', models.CharField(blank=True, help_text='E.g. Boarding, Day, Playgroup', max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_heads', to='schools.school')),
            ],
            options={
                'verbose_name': 'Fee Vote Head',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school')),
                ('vote_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.votehead')),
            ],
            options={
                'unique_together': {('school', 'year', 'term', 'vote_head')},
            },
        ),
    ]
