# Generated by Django 5.2.6 on 2025-09-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='feebalance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_balances', to='schools.school'),
        ),
        migrations.AddField(
            model_name='feebalance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_balances', to='students.student'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='students.student'),
        ),
        migrations.AddField(
            model_name='votehead',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_heads', to='schools.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='vote_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.votehead'),
        ),
        migrations.AddField(
            model_name='feebalance',
            name='vote_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.votehead'),
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='vote_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.votehead'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'year', 'term', 'vote_head')},
        ),
        migrations.AlterUniqueTogether(
            name='feebalance',
            unique_together={('school', 'student', 'vote_head', 'year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='debittransaction',
            unique_together={('school', 'student', 'vote_head', 'year', 'term')},
        ),
    ]
