# Generated by Django 5.2 on 2025-07-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_paymenttransaction'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveSmallIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_invoiced', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_balances', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_balances', to='students.student')),
                ('vote_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.votehead')),
            ],
            options={
                'unique_together': {('school', 'student', 'vote_head', 'year', 'term')},
            },
        ),
    ]
