# Generated by Django 5.2 on 2025-07-13 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feebalance'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('vote_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.votehead')),
            ],
            options={
                'unique_together': {('school', 'student', 'vote_head', 'year', 'term')},
            },
        ),
    ]
