# Generated by Django 6.0.5 on 2026-05-29 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_scheduled_export_job'),
        ('schools', '0004_phase4_communications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REPROCESS', 'Reprocess'), ('TERM_CLOSE', 'Term Close'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('EXPORT', 'Export')], max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object affected (e.g. payment, term close, etc)', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context or parameters for the action')),
                ('result', models.CharField(blank=True, help_text='Result status, e.g. SUCCESS, FAILURE', max_length=32)),
                ('message', models.TextField(blank=True, help_text='Optional message or error details')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_activity_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fees_finance_activity_log',
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
