<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-09 14:19
=======
# Generated by Django 5.2.4 on 2025-07-17 07:43
>>>>>>> ac7828269a6664fd6413e1756f459d58d5f507b1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Subject code (e.g., ENG, MAT, SCI)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=True, help_text='Is this a core subject?')),
                ('grade_levels', models.CharField(default='1-8', help_text='Grade levels this subject is taught (e.g., 1-8, 4-8)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
    ]
