# Generated by Django 5.2 on 2025-11-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_in", models.TimeField()),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(default="present", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "unique_together": {("student", "date")},
            },
        ),
    ]
