# Generated by Django 5.2 on 2025-11-17 06:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("students", "0002_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "employee_no",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "tsc_number",
                    models.CharField(
                        help_text="Teachers Service Commission Number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("passport_no", models.CharField(blank=True, max_length=50)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Kenyan phone number",
                                regex="^\\+?254[0-9]{9}$|^0[0-9]{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "staff_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Teaching Staff", "Teaching Staff"),
                            ("Administrative Staff", "Administrative Staff"),
                            ("Support Staff", "Support Staff"),
                        ],
                        max_length=100,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Contract", "Contract"),
                            ("Part-Time", "Part-Time"),
                            ("Temporary", "Temporary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("On Leave", "On Leave"),
                            ("Suspended", "Suspended"),
                            ("Terminated", "Terminated"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("kra_pin", models.CharField(blank=True, max_length=50)),
                ("nhif_number", models.CharField(blank=True, max_length=50)),
                ("nssf_number", models.CharField(blank=True, max_length=50)),
                ("salary_scale", models.CharField(blank=True, max_length=50)),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "house_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "responsibility_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "teachers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.IntegerField(default=2025)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.class"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Subject Assignment",
                "verbose_name_plural": "Teacher Subject Assignments",
                "db_table": "teacher_subject_assignments",
                "ordering": ["teacher", "subject"],
                "unique_together": {
                    ("teacher", "subject", "class_assigned", "stream", "academic_year")
                },
            },
        ),
    ]
