# Generated by Django 5.2 on 2025-11-16 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
