# Generated by Django 5.2 on 2025-07-18 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('settings', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.IntegerField(default=2025)),
                ('exam_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='students.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='settings.termsetting')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examtype')),
            ],
            options={
                'ordering': ['-exam_date'],
                'unique_together': {('name', 'exam_type', 'subject', 'class_assigned', 'stream', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2025)),
                ('grade', models.CharField(max_length=2)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'db_table': 'grade_scales',
                'ordering': ['-min_score'],
                'unique_together': {('school', 'academic_year', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='ReportCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exams', models.ManyToManyField(related_name='reportcard_configs', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcard_configs', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.termsetting')),
            ],
            options={
                'verbose_name': 'Report Card Config',
                'verbose_name_plural': 'Report Card Configs',
                'unique_together': {('school', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ReportCardExamSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(default=2025)),
                ('is_included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_selections', to='exams.examtype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_selections', to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_selections', to='settings.termsetting')),
            ],
            options={
                'ordering': ['exam_type'],
                'unique_together': {('school', 'term', 'academic_year', 'exam_type')},
            },
        ),
    ]
