# Generated by Django 5.2 on 2025-09-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.class'),
        ),
    ]
