# Generated by Django 5.2.6 on 2025-09-13 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('schools', '0001_initial'),
        ('settings', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='students.stream'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='settings.termsetting'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='schools.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='reportcardconfig',
            name='configured_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcardconfig',
            name='exams',
            field=models.ManyToManyField(related_name='reportcard_configs', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='reportcardconfig',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcard_configs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='reportcardconfig',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.termsetting'),
        ),
        migrations.AddField(
            model_name='reportcardexamselection',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_selections', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='reportcardexamselection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_selections', to='schools.school'),
        ),
        migrations.AddField(
            model_name='reportcardexamselection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_selections', to='settings.termsetting'),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'exam_type', 'subject', 'class_assigned', 'stream', 'term', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('school', 'academic_year', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcardconfig',
            unique_together={('school', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcardexamselection',
            unique_together={('school', 'term', 'academic_year', 'exam_type')},
        ),
    ]
