# Generated by Django 5.2 on 2026-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="academic_year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="gradescale",
            name="academic_year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="reportcardexamselection",
            name="academic_year",
            field=models.IntegerField(default=2026),
        ),
    ]
