from django.db.models.signals import pre_save
from django.dispatch import receiver
from .models import Student
from apps.core.middleware import get_current_school

@receiver(pre_save, sender=Student)
def set_school_from_middleware(sender, instance, **kwargs):
    # Ensure school is set from middleware context when not explicitly provided.
    # Admission number is generated by the DB sequence via the column db_default;
    # do not generate it here.
    if not instance.school:
        instance.school = get_current_school()
