# Generated by Django 5.2 on 2025-07-13 11:36

from django.db import migrations
import uuid 

def generate_codes(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    for school in School.objects.filter(code__isnull=True):
        school.code = uuid.uuid4().hex[:8].upper()
        school.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(generate_codes),
    ]
