# Generated by Django 5.2 on 2025-07-13 11:43

from django.db import migrations

def populate_codes(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    for i, school in enumerate(School.objects.filter(code='').order_by('id'), start=1):
        school.code = f"SCH{i:04d}"
        school.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20250713_1436'),
    ]

    operations = [
        migrations.RunPython(populate_codes),
    ]
