# Generated by Django 5.2 on 2025-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_populate_school_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
