# Generated by Django 5.2 on 2026-07-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_phase4_communications"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
