-- =============================================
-- Subject Management Enhancement Migration
-- =============================================

-- 1. Create subject_categories table
CREATE TABLE IF NOT EXISTS public.subject_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  school_id BIGINT NOT NULL REFERENCES public.schools_school(id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(name, school_id)
);

-- Enable RLS on subject_categories
ALTER TABLE public.subject_categories ENABLE ROW LEVEL SECURITY;

-- RLS policies for subject_categories
CREATE POLICY "Users can view categories from their school"
  ON public.subject_categories FOR SELECT
  USING (school_id = get_user_school_id());

CREATE POLICY "Users can create categories for their school"
  ON public.subject_categories FOR INSERT
  WITH CHECK (school_id = get_user_school_id());

CREATE POLICY "Users can update categories from their school"
  ON public.subject_categories FOR UPDATE
  USING (school_id = get_user_school_id())
  WITH CHECK (school_id = get_user_school_id());

CREATE POLICY "Users can delete categories from their school"
  ON public.subject_categories FOR DELETE
  USING (school_id = get_user_school_id());

-- 2. Add new columns to subjects table
ALTER TABLE public.subjects 
  ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.subject_categories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS school_id BIGINT REFERENCES public.schools_school(id) ON DELETE CASCADE;

-- Enable RLS on subjects (if not already enabled)
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Users can view subjects from their school" ON public.subjects;
DROP POLICY IF EXISTS "Users can create subjects for their school" ON public.subjects;
DROP POLICY IF EXISTS "Users can update subjects from their school" ON public.subjects;
DROP POLICY IF EXISTS "Users can delete subjects from their school" ON public.subjects;

-- Create RLS policies for subjects
CREATE POLICY "Users can view subjects from their school"
  ON public.subjects FOR SELECT
  USING (school_id = get_user_school_id() OR school_id IS NULL);

CREATE POLICY "Users can create subjects for their school"
  ON public.subjects FOR INSERT
  WITH CHECK (school_id = get_user_school_id());

CREATE POLICY "Users can update subjects from their school"
  ON public.subjects FOR UPDATE
  USING (school_id = get_user_school_id() OR school_id IS NULL)
  WITH CHECK (school_id = get_user_school_id());

CREATE POLICY "Users can delete subjects from their school"
  ON public.subjects FOR DELETE
  USING (school_id = get_user_school_id());

-- 3. Create class_subjects table for class-subject allocations
CREATE TABLE IF NOT EXISTS public.class_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
  teacher_id BIGINT REFERENCES public.teachers(id) ON DELETE SET NULL,
  school_id BIGINT NOT NULL REFERENCES public.schools_school(id) ON DELETE CASCADE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  periods_per_week INTEGER DEFAULT 3,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(class_id, subject_id)
);

-- Enable RLS on class_subjects
ALTER TABLE public.class_subjects ENABLE ROW LEVEL SECURITY;

-- RLS policies for class_subjects
CREATE POLICY "Users can view class subjects from their school"
  ON public.class_subjects FOR SELECT
  USING (school_id = get_user_school_id());

CREATE POLICY "Users can create class subjects for their school"
  ON public.class_subjects FOR INSERT
  WITH CHECK (school_id = get_user_school_id());

CREATE POLICY "Users can update class subjects from their school"
  ON public.class_subjects FOR UPDATE
  USING (school_id = get_user_school_id())
  WITH CHECK (school_id = get_user_school_id());

CREATE POLICY "Users can delete class subjects from their school"
  ON public.class_subjects FOR DELETE
  USING (school_id = get_user_school_id());

-- 4. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_subject_categories_school ON public.subject_categories(school_id);
CREATE INDEX IF NOT EXISTS idx_subjects_category ON public.subjects(category_id);
CREATE INDEX IF NOT EXISTS idx_subjects_school ON public.subjects(school_id);
CREATE INDEX IF NOT EXISTS idx_subjects_active ON public.subjects(is_active);
CREATE INDEX IF NOT EXISTS idx_class_subjects_class ON public.class_subjects(class_id);
CREATE INDEX IF NOT EXISTS idx_class_subjects_subject ON public.class_subjects(subject_id);
CREATE INDEX IF NOT EXISTS idx_class_subjects_teacher ON public.class_subjects(teacher_id);
CREATE INDEX IF NOT EXISTS idx_class_subjects_school ON public.class_subjects(school_id);

-- 5. Create function to check subject dependencies before deletion
CREATE OR REPLACE FUNCTION public.check_subject_dependencies(p_subject_id BIGINT)
RETURNS TABLE(
  has_dependencies BOOLEAN,
  class_count INTEGER,
  teacher_count INTEGER,
  exam_count INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_class_count INTEGER;
  v_teacher_count INTEGER;
  v_exam_count INTEGER;
BEGIN
  -- Count class allocations
  SELECT COUNT(*) INTO v_class_count
  FROM public.class_subjects
  WHERE subject_id = p_subject_id;
  
  -- Count teacher specializations
  SELECT COUNT(*) INTO v_teacher_count
  FROM public.teacher_specializations
  WHERE subject_id = p_subject_id;
  
  -- Count exams
  SELECT COUNT(*) INTO v_exam_count
  FROM public.exams_exam
  WHERE subject_id = p_subject_id;
  
  RETURN QUERY SELECT 
    (v_class_count > 0 OR v_teacher_count > 0 OR v_exam_count > 0) AS has_dependencies,
    v_class_count AS class_count,
    v_teacher_count AS teacher_count,
    v_exam_count AS exam_count;
END;
$$;

-- 6. Create function to get subject statistics
CREATE OR REPLACE FUNCTION public.get_subject_stats(p_subject_id BIGINT)
RETURNS TABLE(
  assigned_classes INTEGER,
  assigned_teachers INTEGER,
  total_exams INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY SELECT 
    (SELECT COUNT(*)::INTEGER FROM public.class_subjects WHERE subject_id = p_subject_id AND is_active = true) AS assigned_classes,
    (SELECT COUNT(*)::INTEGER FROM public.teacher_specializations WHERE subject_id = p_subject_id) AS assigned_teachers,
    (SELECT COUNT(*)::INTEGER FROM public.exams_exam WHERE subject_id = p_subject_id) AS total_exams;
END;
$$;

-- 7. Create trigger for updated_at on new tables
CREATE OR REPLACE FUNCTION public.update_subject_tables_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_subject_categories_updated_at ON public.subject_categories;
CREATE TRIGGER update_subject_categories_updated_at
  BEFORE UPDATE ON public.subject_categories
  FOR EACH ROW
  EXECUTE FUNCTION public.update_subject_tables_updated_at();

DROP TRIGGER IF EXISTS update_class_subjects_updated_at ON public.class_subjects;
CREATE TRIGGER update_class_subjects_updated_at
  BEFORE UPDATE ON public.class_subjects
  FOR EACH ROW
  EXECUTE FUNCTION public.update_subject_tables_updated_at();