-- Add HOD and workload limit columns to teachers
ALTER TABLE public.teachers 
ADD COLUMN IF NOT EXISTS is_hod BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS weekly_workload_limit INTEGER DEFAULT 28,
ADD COLUMN IF NOT EXISTS current_workload INTEGER DEFAULT 0;

-- Create teacher availability table
CREATE TABLE IF NOT EXISTS public.teacher_availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 0=Sunday, 1=Monday, etc.
  start_time TIME NOT NULL DEFAULT '08:00',
  end_time TIME NOT NULL DEFAULT '17:00',
  is_available BOOLEAN DEFAULT true,
  reason TEXT,
  school_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(teacher_id, day_of_week)
);

-- Create teacher specializations table (subjects they can teach)
CREATE TABLE IF NOT EXISTS public.teacher_specializations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
  proficiency_level VARCHAR(20) DEFAULT 'Intermediate' CHECK (proficiency_level IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
  is_primary BOOLEAN DEFAULT false,
  years_experience INTEGER DEFAULT 0,
  school_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(teacher_id, subject_id)
);

-- Create teacher workload tracking table
CREATE TABLE IF NOT EXISTS public.teacher_workload (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  stream_id BIGINT REFERENCES public.streams(id) ON DELETE SET NULL,
  subject_id BIGINT NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
  lessons_per_week INTEGER NOT NULL DEFAULT 1,
  is_class_teacher BOOLEAN DEFAULT false,
  academic_year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  term INTEGER NOT NULL DEFAULT 1,
  school_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(teacher_id, class_id, stream_id, subject_id, academic_year, term)
);

-- Enable RLS on new tables
ALTER TABLE public.teacher_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_specializations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_workload ENABLE ROW LEVEL SECURITY;

-- RLS policies for teacher_availability
CREATE POLICY "Users can view availability from their school" ON public.teacher_availability
  FOR SELECT USING (school_id = get_user_school_id());
CREATE POLICY "Users can create availability for their school" ON public.teacher_availability
  FOR INSERT WITH CHECK (school_id = get_user_school_id());
CREATE POLICY "Users can update availability from their school" ON public.teacher_availability
  FOR UPDATE USING (school_id = get_user_school_id());
CREATE POLICY "Users can delete availability from their school" ON public.teacher_availability
  FOR DELETE USING (school_id = get_user_school_id());

-- RLS policies for teacher_specializations
CREATE POLICY "Users can view specializations from their school" ON public.teacher_specializations
  FOR SELECT USING (school_id = get_user_school_id());
CREATE POLICY "Users can create specializations for their school" ON public.teacher_specializations
  FOR INSERT WITH CHECK (school_id = get_user_school_id());
CREATE POLICY "Users can update specializations from their school" ON public.teacher_specializations
  FOR UPDATE USING (school_id = get_user_school_id());
CREATE POLICY "Users can delete specializations from their school" ON public.teacher_specializations
  FOR DELETE USING (school_id = get_user_school_id());

-- RLS policies for teacher_workload
CREATE POLICY "Users can view workload from their school" ON public.teacher_workload
  FOR SELECT USING (school_id = get_user_school_id());
CREATE POLICY "Users can create workload for their school" ON public.teacher_workload
  FOR INSERT WITH CHECK (school_id = get_user_school_id());
CREATE POLICY "Users can update workload from their school" ON public.teacher_workload
  FOR UPDATE USING (school_id = get_user_school_id());
CREATE POLICY "Users can delete workload from their school" ON public.teacher_workload
  FOR DELETE USING (school_id = get_user_school_id());

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_teacher_availability_teacher ON public.teacher_availability(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_specializations_teacher ON public.teacher_specializations(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_specializations_subject ON public.teacher_specializations(subject_id);
CREATE INDEX IF NOT EXISTS idx_teacher_workload_teacher ON public.teacher_workload(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_workload_class ON public.teacher_workload(class_id);

-- Function to calculate teacher workload
CREATE OR REPLACE FUNCTION public.calculate_teacher_workload(p_teacher_id BIGINT)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
  total_lessons INTEGER;
BEGIN
  SELECT COALESCE(SUM(lessons_per_week), 0) INTO total_lessons
  FROM public.teacher_workload
  WHERE teacher_id = p_teacher_id
    AND academic_year = EXTRACT(YEAR FROM CURRENT_DATE);
  
  -- Update the teacher's current workload
  UPDATE public.teachers SET current_workload = total_lessons WHERE id = p_teacher_id;
  
  RETURN total_lessons;
END;
$$;

-- Function to check if teacher can teach a subject
CREATE OR REPLACE FUNCTION public.can_teacher_teach_subject(p_teacher_id BIGINT, p_subject_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.teacher_specializations
    WHERE teacher_id = p_teacher_id AND subject_id = p_subject_id
  );
END;
$$;

-- Trigger to update workload when assignments change
CREATE OR REPLACE FUNCTION public.update_teacher_workload_trigger()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    PERFORM calculate_teacher_workload(NEW.teacher_id);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM calculate_teacher_workload(OLD.teacher_id);
    RETURN OLD;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS trigger_update_teacher_workload ON public.teacher_workload;
CREATE TRIGGER trigger_update_teacher_workload
  AFTER INSERT OR UPDATE OR DELETE ON public.teacher_workload
  FOR EACH ROW
  EXECUTE FUNCTION update_teacher_workload_trigger();

-- Update timestamps trigger
DROP TRIGGER IF EXISTS update_teacher_availability_updated_at ON public.teacher_availability;
CREATE TRIGGER update_teacher_availability_updated_at
  BEFORE UPDATE ON public.teacher_availability
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_teacher_workload_updated_at ON public.teacher_workload;
CREATE TRIGGER update_teacher_workload_updated_at
  BEFORE UPDATE ON public.teacher_workload
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();