-- Add new columns to teachers table for enhanced teacher management
ALTER TABLE public.teachers 
ADD COLUMN IF NOT EXISTS is_hod BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS weekly_workload_limit INTEGER DEFAULT 28,
ADD COLUMN IF NOT EXISTS available_days TEXT[] DEFAULT ARRAY['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
ADD COLUMN IF NOT EXISTS unavailable_dates TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS qualifications TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';

-- Create teacher_subjects table for subject specialization (subjects a teacher CAN teach)
CREATE TABLE IF NOT EXISTS public.teacher_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
  qualification_level VARCHAR(50) DEFAULT 'Qualified',
  is_primary_subject BOOLEAN DEFAULT false,
  years_experience INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(teacher_id, subject_id)
);

-- Create leave_requests table for leave management
CREATE TABLE IF NOT EXISTS public.leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  leave_type VARCHAR(50) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  days_requested INTEGER NOT NULL,
  reason TEXT,
  status VARCHAR(20) DEFAULT 'Pending',
  approved_by BIGINT REFERENCES public.users(id),
  approved_at TIMESTAMP WITH TIME ZONE,
  rejection_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Add unique constraint on staff_attendance for upsert
ALTER TABLE public.staff_attendance 
DROP CONSTRAINT IF EXISTS staff_attendance_staff_date_unique;

ALTER TABLE public.staff_attendance 
ADD CONSTRAINT staff_attendance_staff_date_unique UNIQUE (staff_id, date);

-- Enable RLS on new tables
ALTER TABLE public.teacher_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;

-- RLS policies for teacher_subjects
CREATE POLICY "Users can view teacher subjects from their school"
ON public.teacher_subjects FOR SELECT
USING (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = teacher_subjects.teacher_id 
  AND t.school_id = get_user_school_id()
));

CREATE POLICY "Users can create teacher subjects for their school"
ON public.teacher_subjects FOR INSERT
WITH CHECK (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = teacher_subjects.teacher_id 
  AND t.school_id = get_user_school_id()
));

CREATE POLICY "Users can update teacher subjects from their school"
ON public.teacher_subjects FOR UPDATE
USING (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = teacher_subjects.teacher_id 
  AND t.school_id = get_user_school_id()
));

CREATE POLICY "Users can delete teacher subjects from their school"
ON public.teacher_subjects FOR DELETE
USING (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = teacher_subjects.teacher_id 
  AND t.school_id = get_user_school_id()
));

-- RLS policies for leave_requests
CREATE POLICY "Users can view leave requests from their school"
ON public.leave_requests FOR SELECT
USING (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = leave_requests.staff_id 
  AND t.school_id = get_user_school_id()
));

CREATE POLICY "Users can create leave requests for their school"
ON public.leave_requests FOR INSERT
WITH CHECK (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = leave_requests.staff_id 
  AND t.school_id = get_user_school_id()
));

CREATE POLICY "Users can update leave requests from their school"
ON public.leave_requests FOR UPDATE
USING (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = leave_requests.staff_id 
  AND t.school_id = get_user_school_id()
));

CREATE POLICY "Users can delete leave requests from their school"
ON public.leave_requests FOR DELETE
USING (EXISTS (
  SELECT 1 FROM public.teachers t 
  WHERE t.id = leave_requests.staff_id 
  AND t.school_id = get_user_school_id()
));

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_teacher_subjects_teacher_id ON public.teacher_subjects(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teacher_subjects_subject_id ON public.teacher_subjects(subject_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_staff_id ON public.leave_requests(staff_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_date ON public.staff_attendance(date);
CREATE INDEX IF NOT EXISTS idx_teacher_subject_assignments_teacher ON public.teacher_subject_assignments(teacher_id);